version: "3.9"

services:
  hello1:
    build: .
    image: hello:v0.2
    volumes:
      - hello1-volume:/tmp
  hello2:
    build: .
    image: hello:v0.2
    volumes:
      - hello2-volume:/tmp

volumes:
  hello1-volume:
  hello2-volume: